# Multilayer Perceptron: Logic Gates

In [1]:
import numpy as np
import pandas as pd

import sys
sys.path.insert(0, '../neural_networks/')
from multilayer_perceptron import MultiLayerPerceptron

In [2]:
dataset = pd.read_csv('../dataset/logic_gates/and_or_2.csv', header=None)
dataset_xor = pd.read_csv('../dataset/logic_gates/xor_2.csv', header=None)

X = dataset_xor.iloc[:,:-1].values
y_xor = dataset_xor.iloc[:,-1].values
y_and = dataset.iloc[:,-2].values
y_or = dataset.iloc[:,-1].values

## AND (2):

In [3]:
mlp = MultiLayerPerceptron()
mlp.add_layer(2, 0.1, 'tanh') 
mlp.add_layer(1, 0.1, 'tanh') 
mlp.fit(X, y_and, epochs=500, error_max=1e-6)
mlp.predict(X)

array([[-0.99944996],
       [-0.96762815],
       [-0.9637792 ],
       [ 0.95247074]])

## OR (2):

In [4]:
mlp = MultiLayerPerceptron()
mlp.add_layer(2, 0.1, 'tanh') 
mlp.add_layer(1, 0.1, 'tanh') 
mlp.fit(X, y_or, epochs=500, error_max=1e-6)
mlp.predict(X)

array([[-0.95695595],
       [ 0.96714502],
       [ 0.97312978],
       [ 0.99651065]])

## XOR (2):

In [5]:
mlp = MultiLayerPerceptron()
mlp.add_layer(2, 0.1, 'tanh') 
mlp.add_layer(1, 0.1, 'tanh') 
mlp.fit(X, y_xor, epochs=500, error_max=1e-6)
mlp.predict(X)

array([[-0.93399577],
       [ 0.94319464],
       [ 0.94393081],
       [-0.92519271]])

In [6]:
dataset = pd.read_csv('../dataset/logic_gates/and_or_3.csv', header=None)
dataset_xor = pd.read_csv('../dataset/logic_gates/xor_3.csv', header=None)

X = dataset_xor.iloc[:,:-1].values
y_xor = dataset_xor.iloc[:,-1].values
y_and = dataset.iloc[:,-2].values
y_or = dataset.iloc[:,-1].values

## AND (3):

In [7]:
mlp = MultiLayerPerceptron()
mlp.add_layer(2, 0.1, 'tanh') 
mlp.add_layer(1, 0.1, 'tanh') 
mlp.fit(X, y_and, epochs=500, error_max=1e-6)
mlp.predict(X)

array([[-0.99995222],
       [-0.99977585],
       [-0.99985823],
       [-0.99955764],
       [-0.96959544],
       [-0.96465834],
       [-0.96778988],
       [ 0.94438678]])

## OR (3):

In [8]:
mlp = MultiLayerPerceptron()
mlp.add_layer(2, 0.1, 'tanh') 
mlp.add_layer(1, 0.1, 'tanh') 
mlp.fit(X, y_or, epochs=500, error_max=1e-6)
mlp.predict(X)

array([[-0.95467224],
       [ 0.97503473],
       [ 0.9720681 ],
       [ 0.97689737],
       [ 0.99763678],
       [ 0.99847841],
       [ 0.99822369],
       [ 0.99887836]])

## XOR (3):

In [9]:
mlp = MultiLayerPerceptron()
mlp.add_layer(2, 0.1, 'tanh') 
mlp.add_layer(1, 0.1, 'tanh') 
mlp.fit(X, y_xor, epochs=500, error_max=1e-6)
mlp.predict(X)

array([[-0.93681414],
       [ 0.98045405],
       [ 0.97881195],
       [ 0.98498801],
       [ 0.95777157],
       [ 0.95680953],
       [ 0.95633146],
       [-0.92409693]])